version: '3.8'

services:
  app:
    image: dockerdemo:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo?autoReconnect=true&allowPublickeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Nitheeshreddy143@
    depends_on:
      - db

  db:
    image: mysql:8.0.27

    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: Nitheeshreddy143@
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: Nitheeshreddy143